.\" Man page for LiteFM
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.TH LiteFM 1 "July 2024" "1.0" "Lite File Manager in NCurses"
.SH NAME
LiteFM \- A LIGHT AND FAST terminal-based file explorer using NCurses
.SH SYNOPSIS
.B LiteFM
.SH DESCRIPTION
.B LiteFM
is a simple file manager that runs in the terminal using the NCurses library. It allows users to navigate directories, view file information, create ,delete, move files and directories, and extract archives.
.SH USAGE
The following keys are used to navigate and perform actions within 
.B LiteFM:
.TP
.B UP/k
Move the selection up.
.TP
.B DOWN/j
Move the selection down.
.TP
.B LEFT/h
Move to the parent directory.
.TP
.B RIGHT/l
Enter the selected subdirectory.
.TP
.B .
Toggle the display of hidden files and directories.
.TP
.B a
Add a new file or directory. To create a directory, append a '/' to the name.
.TP
.B H
Go to the `/` directory.
.TP
.B gh
Go to the /home/$USER (~) directory.
.TP
.B gt
Go to the directory as given by the input.
.TP
.B d
Delete the selected file or directory (NON-RECURSIVE DELETION).
.TP
.B G
Go to the bottom of the currently viewing list.
.TP
.B gg
Go to the top of the currently viewing list.
.TP
.B M
Move a selected file/dir to the user's choice of destination.
.TP
.B D
Delete a directory RECURSIVELY (every sub-dir and file inside selected dir is deleted).
.TP
.B R
Rename a file or directory.
.TP
.B /
Search for a file or directory.
.TP
.B E
Extract the selected archive (zip or tar).
.TP
.B Z
To compress a directory to zip or tar(*).
* - If you extract a zip file and attempt to compress it to a tar, or vice-versa, it will NOT WORK (it will show up as empty)!
.TP
.B Enter
Display information about the selected file (if file preview is displayed).
.TP
.B n
Go to the next occurance of the string search '/'.
.TP
.B N
Go to the previous occurance of the string search '/'.
.TP
.B q
Quit the application.
.TP
.B y
Yank the current file location of selected item.
.TP
.B Y
Yank the current file content.
.SH OPTIONS
.B LiteFM
does not take any command-line options.
.SH FILES
.B LiteFM
operates on the file system and does not rely on any specific configuration files.
.SH EXAMPLES
To start 
.B LiteFM,
simply run:
.PP
.EX
lfm
.EE
.PP
Navigate to the desired directory using the arrow keys or 
.B h
and 
.B l.
Create or delete files and directories using 
.B a
and 
.B d.
Extract archives using 
.B e,
and search for files or directories using 
.B /.
.SH AUTHOR - nots1dd
.B LiteFM
was developed as an example application using the NCurses library.
.SH SEE ALSO
.BR ncurses (3), 
.BR dirent (3), 
.BR unzip (1), 
.BR tar (1)
.SH BUGS
No known bugs. Report any issues to the project maintainer (https://github.com/nots1dd/litefm).
.SH COPYRIGHT
This is free software licensed under GNU GPL v3; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
